import perfume1 from '../assets/perfumes/perfume1.jpeg';
import perfume2 from '../assets/perfumes/perfume2.jpeg';
import perfume3 from '../assets/perfumes/perfume3.jpeg';
import perfume4 from '../assets/perfumes/perfume4.jpeg';
import perfume5 from '../assets/perfumes/perfume5.jpeg';
import perfume6 from '../assets/perfumes/perfume6.jpeg';
import perfume7 from '../assets/perfumes/perfume7.jpeg';
import perfume8 from '../assets/perfumes/perfume8.jpeg';
import perfume9 from '../assets/perfumes/perfume9.jpeg';

const imagePool = [perfume1, perfume2, perfume3, perfume4, perfume5, perfume6, perfume7, perfume8, perfume9];

const createProduct = (overrides) => ({
  id: overrides.slug,
  slug: overrides.slug,
  name: overrides.name,
  brand: overrides.brand || 'Oud Kraft',
  category: overrides.category,
  gender: overrides.gender,
  inspiration: overrides.inspiration,
  description: overrides.description,
  detailedDescription: overrides.detailedDescription || overrides.description,
  story: overrides.story || overrides.description,
  howToWear: overrides.howToWear || 'Apply to warm skin and let the scent evolve gracefully over the day.',
  whenToWear: overrides.whenToWear || 'Perfect for evenings, special occasions, and confident daily wear.',
  season: overrides.season || 'All year',
  occasion: overrides.occasion || 'Evening',
  sillage: overrides.sillage || 'Moderate',
  price: overrides.price,
  oldPrice: overrides.oldPrice,
  discount: overrides.discount,
  size: overrides.size,
  images: overrides.images.map((index) => imagePool[index - 1]),
  image360: overrides.image360 ? imagePool[overrides.image360 - 1] : imagePool[overrides.images[0] - 1],
  fragranceFamily: overrides.fragranceFamily,
  topNotes: overrides.topNotes,
  heartNotes: overrides.heartNotes,
  baseNotes: overrides.baseNotes,
  middleNotes: overrides.middleNotes || overrides.heartNotes,
  longevity: overrides.longevity,
  projection: overrides.projection,
  stock: overrides.stock,
  rating: overrides.rating,
  reviewCount: overrides.reviewCount,
  featured: overrides.featured,
  bestseller: overrides.bestseller,
  delivery: overrides.delivery,
  notes: overrides.notes,
  sku: overrides.sku,
  ingredients: overrides.ingredients || ['Natural oud resin', 'Rare florals', 'Velvet woods'],
  usage: overrides.usage || 'Apply to warm skin and let the scent evolve gracefully over the day.',
  deliveryInfo: overrides.deliveryInfo || 'Complimentary delivery within the UAE and elegant gift-ready packaging.',
  reviews: overrides.reviews || [],
  questions: overrides.questions || []
});

export const products = [
  createProduct({
    slug: "brazilian-tobacco",
    name: "Brazilian Tobacco",
    category: "Luxury Collection",
    gender: "Men",
    fragranceFamily: "Woody",
    topNotes: ["Tobacco", "Bergamot", "Orange"],
    heartNotes: ["Rose", "Cardamom", "Cocoa"],
    baseNotes: ["Oud", "Vanilla", "Leather"],
    occasion: "Evening",
    season: "Autumn",
    sillage: "Strong",
    story: "A rich, velvety tobacco blend that captures bold warmth and refined elegance. Modern, smoky and intensely luxurious.",
    howToWear: "Spray lightly on pulse points for a deep warm trail. Ideal for evening occasions and formal evenings.",
    whenToWear: "Perfect for autumn and winter evenings, celebrations and refined nights out.",
    longevity: "10+ hours",
    projection: "Strong",
    size: "100 ml",
    price: 279,
    oldPrice: 349,
    discount: "20%",
    stock: 14,
    rating: 4.9,
    reviewCount: 86,
    featured: true,
    bestseller: true,
    delivery: "Signature packaging included.",
    notes: ["Smoky tobacco", "Velvety oud"],
    images: [1, 2, 3],
    image360: 1
  }),
  createProduct({
    slug: "brazilian-tobacco-50-ml",
    name: "Brazilian Tobacco (50 ml)",
    category: "Luxury Collection",
    gender: "Men",
    fragranceFamily: "Woody",
    topNotes: ["Tobacco", "Bergamot", "Orange"],
    heartNotes: ["Rose", "Cardamom", "Cocoa"],
    baseNotes: ["Oud", "Vanilla", "Leather"],
    occasion: "Evening",
    season: "Autumn",
    sillage: "Strong",
    story: "A rich, velvety tobacco blend that captures bold warmth and refined elegance. Modern, smoky and intensely luxurious.",
    howToWear: "Spray lightly on pulse points for a deep warm trail. Ideal for evening occasions and formal evenings.",
    whenToWear: "Perfect for autumn and winter evenings, celebrations and refined nights out.",
    longevity: "10+ hours",
    projection: "Strong",
    size: "50 ml",
    price: 209,
    oldPrice: 262,
    discount: "20%",
    stock: 12,
    rating: 4.9,
    reviewCount: 64,
    featured: false,
    bestseller: false,
    delivery: "Signature packaging included.",
    notes: ["Smoky tobacco", "Velvety oud"],
    images: [1, 2, 3],
    image360: 1,
    reviews: [],
    questions: []
  }),
  createProduct({
    slug: "brazilian-tobacco-travel-duo",
    name: "Brazilian Tobacco (Travel Duo)",
    category: "Luxury Collection",
    gender: "Men",
    fragranceFamily: "Woody",
    topNotes: ["Tobacco", "Bergamot", "Orange"],
    heartNotes: ["Rose", "Cardamom", "Cocoa"],
    baseNotes: ["Oud", "Vanilla", "Leather"],
    occasion: "Evening",
    season: "Autumn",
    sillage: "Strong",
    story: "A rich, velvety tobacco blend that captures bold warmth and refined elegance. Modern, smoky and intensely luxurious.",
    howToWear: "Spray lightly on pulse points for a deep warm trail. Ideal for evening occasions and formal evenings.",
    whenToWear: "Perfect for autumn and winter evenings, celebrations and refined nights out.",
    longevity: "10+ hours",
    projection: "Strong",
    size: "Travel Duo",
    price: 251,
    oldPrice: 314,
    discount: "20%",
    stock: 12,
    rating: 4.9,
    reviewCount: 77,
    featured: false,
    bestseller: false,
    delivery: "Signature packaging included.",
    notes: ["Smoky tobacco", "Velvety oud"],
    images: [1, 2, 3],
    image360: 1,
    reviews: [],
    questions: []
  }),
  createProduct({
    slug: "brazilian-tobacco-gift-set",
    name: "Brazilian Tobacco (Gift Set)",
    category: "Luxury Collection",
    gender: "Men",
    fragranceFamily: "Woody",
    topNotes: ["Tobacco", "Bergamot", "Orange"],
    heartNotes: ["Rose", "Cardamom", "Cocoa"],
    baseNotes: ["Oud", "Vanilla", "Leather"],
    occasion: "Evening",
    season: "Autumn",
    sillage: "Strong",
    story: "A rich, velvety tobacco blend that captures bold warmth and refined elegance. Modern, smoky and intensely luxurious.",
    howToWear: "Spray lightly on pulse points for a deep warm trail. Ideal for evening occasions and formal evenings.",
    whenToWear: "Perfect for autumn and winter evenings, celebrations and refined nights out.",
    longevity: "10+ hours",
    projection: "Strong",
    size: "Gift Set",
    price: 335,
    oldPrice: 419,
    discount: "20%",
    stock: 12,
    rating: 4.9,
    reviewCount: 103,
    featured: false,
    bestseller: false,
    delivery: "Signature packaging included.",
    notes: ["Smoky tobacco", "Velvety oud"],
    images: [1, 2, 3],
    image360: 1,
    reviews: [],
    questions: []
  }),
  createProduct({
    slug: "brazilian-tobacco-travel-trio",
    name: "Brazilian Tobacco (Travel Trio)",
    category: "Luxury Collection",
    gender: "Men",
    fragranceFamily: "Woody",
    topNotes: ["Tobacco", "Bergamot", "Orange"],
    heartNotes: ["Rose", "Cardamom", "Cocoa"],
    baseNotes: ["Oud", "Vanilla", "Leather"],
    occasion: "Evening",
    season: "Autumn",
    sillage: "Strong",
    story: "A rich, velvety tobacco blend that captures bold warmth and refined elegance. Modern, smoky and intensely luxurious.",
    howToWear: "Spray lightly on pulse points for a deep warm trail. Ideal for evening occasions and formal evenings.",
    whenToWear: "Perfect for autumn and winter evenings, celebrations and refined nights out.",
    longevity: "10+ hours",
    projection: "Strong",
    size: "Travel Trio",
    price: 237,
    oldPrice: 297,
    discount: "20%",
    stock: 12,
    rating: 4.9,
    reviewCount: 73,
    featured: false,
    bestseller: false,
    delivery: "Signature packaging included.",
    notes: ["Smoky tobacco", "Velvety oud"],
    images: [1, 2, 3],
    image360: 1,
    reviews: [],
    questions: []
  }),
  createProduct({
    slug: "spanish-tobacco",
    name: "Spanish Tobacco",
    category: "Luxury Collection",
    gender: "Men",
    fragranceFamily: "Amber",
    topNotes: ["Cinnamon", "Pink Pepper", "Mandarin"],
    heartNotes: ["Tobacco", "Rose", "Incense"],
    baseNotes: ["Oud", "Amber", "Musk"],
    occasion: "Evening",
    season: "Winter",
    sillage: "Strong",
    story: "A vibrant blend inspired by Spanish nights; crisp spice and tobacco balanced by resinous woods for extraordinary depth.",
    howToWear: "Apply to neck and chest after dressing, allowing the spicy warmth to unfold over time.",
    whenToWear: "Best suited for cooler nights, intimate dinners and special celebrations.",
    longevity: "9\u201311 hours",
    projection: "Strong",
    size: "100 ml",
    price: 269,
    oldPrice: 319,
    discount: "16%",
    stock: 10,
    rating: 4.8,
    reviewCount: 74,
    featured: true,
    bestseller: true,
    delivery: "Complimentary gift wrap on orders above AED 300.",
    notes: ["Warm cinnamon", "Resinous trace"],
    images: [2, 3, 4],
    image360: 2
  }),
  createProduct({
    slug: "spanish-tobacco-50-ml",
    name: "Spanish Tobacco (50 ml)",
    category: "Luxury Collection",
    gender: "Men",
    fragranceFamily: "Amber",
    topNotes: ["Cinnamon", "Pink Pepper", "Mandarin"],
    heartNotes: ["Tobacco", "Rose", "Incense"],
    baseNotes: ["Oud", "Amber", "Musk"],
    occasion: "Evening",
    season: "Winter",
    sillage: "Strong",
    story: "A vibrant blend inspired by Spanish nights; crisp spice and tobacco balanced by resinous woods for extraordinary depth.",
    howToWear: "Apply to neck and chest after dressing, allowing the spicy warmth to unfold over time.",
    whenToWear: "Best suited for cooler nights, intimate dinners and special celebrations.",
    longevity: "9\u201311 hours",
    projection: "Strong",
    size: "50 ml",
    price: 202,
    oldPrice: 239,
    discount: "15%",
    stock: 8,
    rating: 4.8,
    reviewCount: 55,
    featured: false,
    bestseller: false,
    delivery: "Complimentary gift wrap on orders above AED 300.",
    notes: ["Warm cinnamon", "Resinous trace"],
    images: [2, 3, 4],
    image360: 2,
    reviews: [],
    questions: []
  }),
  createProduct({
    slug: "spanish-tobacco-travel-duo",
    name: "Spanish Tobacco (Travel Duo)",
    category: "Luxury Collection",
    gender: "Men",
    fragranceFamily: "Amber",
    topNotes: ["Cinnamon", "Pink Pepper", "Mandarin"],
    heartNotes: ["Tobacco", "Rose", "Incense"],
    baseNotes: ["Oud", "Amber", "Musk"],
    occasion: "Evening",
    season: "Winter",
    sillage: "Strong",
    story: "A vibrant blend inspired by Spanish nights; crisp spice and tobacco balanced by resinous woods for extraordinary depth.",
    howToWear: "Apply to neck and chest after dressing, allowing the spicy warmth to unfold over time.",
    whenToWear: "Best suited for cooler nights, intimate dinners and special celebrations.",
    longevity: "9\u201311 hours",
    projection: "Strong",
    size: "Travel Duo",
    price: 242,
    oldPrice: 287,
    discount: "16%",
    stock: 8,
    rating: 4.8,
    reviewCount: 66,
    featured: false,
    bestseller: false,
    delivery: "Complimentary gift wrap on orders above AED 300.",
    notes: ["Warm cinnamon", "Resinous trace"],
    images: [2, 3, 4],
    image360: 2,
    reviews: [],
    questions: []
  }),
  createProduct({
    slug: "spanish-tobacco-gift-set",
    name: "Spanish Tobacco (Gift Set)",
    category: "Luxury Collection",
    gender: "Men",
    fragranceFamily: "Amber",
    topNotes: ["Cinnamon", "Pink Pepper", "Mandarin"],
    heartNotes: ["Tobacco", "Rose", "Incense"],
    baseNotes: ["Oud", "Amber", "Musk"],
    occasion: "Evening",
    season: "Winter",
    sillage: "Strong",
    story: "A vibrant blend inspired by Spanish nights; crisp spice and tobacco balanced by resinous woods for extraordinary depth.",
    howToWear: "Apply to neck and chest after dressing, allowing the spicy warmth to unfold over time.",
    whenToWear: "Best suited for cooler nights, intimate dinners and special celebrations.",
    longevity: "9\u201311 hours",
    projection: "Strong",
    size: "Gift Set",
    price: 323,
    oldPrice: 383,
    discount: "16%",
    stock: 8,
    rating: 4.8,
    reviewCount: 88,
    featured: false,
    bestseller: false,
    delivery: "Complimentary gift wrap on orders above AED 300.",
    notes: ["Warm cinnamon", "Resinous trace"],
    images: [2, 3, 4],
    image360: 2,
    reviews: [],
    questions: []
  }),
  createProduct({
    slug: "spanish-tobacco-travel-trio",
    name: "Spanish Tobacco (Travel Trio)",
    category: "Luxury Collection",
    gender: "Men",
    fragranceFamily: "Amber",
    topNotes: ["Cinnamon", "Pink Pepper", "Mandarin"],
    heartNotes: ["Tobacco", "Rose", "Incense"],
    baseNotes: ["Oud", "Amber", "Musk"],
    occasion: "Evening",
    season: "Winter",
    sillage: "Strong",
    story: "A vibrant blend inspired by Spanish nights; crisp spice and tobacco balanced by resinous woods for extraordinary depth.",
    howToWear: "Apply to neck and chest after dressing, allowing the spicy warmth to unfold over time.",
    whenToWear: "Best suited for cooler nights, intimate dinners and special celebrations.",
    longevity: "9\u201311 hours",
    projection: "Strong",
    size: "Travel Trio",
    price: 229,
    oldPrice: 271,
    discount: "15%",
    stock: 8,
    rating: 4.8,
    reviewCount: 62,
    featured: false,
    bestseller: false,
    delivery: "Complimentary gift wrap on orders above AED 300.",
    notes: ["Warm cinnamon", "Resinous trace"],
    images: [2, 3, 4],
    image360: 2,
    reviews: [],
    questions: []
  }),
  createProduct({
    slug: "polo",
    name: "Polo",
    category: "Eau de Parfum",
    gender: "Men",
    fragranceFamily: "Woody",
    topNotes: ["Lemon", "Sage", "Blackcurrant"],
    heartNotes: ["Leather", "Cedarwood", "Ambergris"],
    baseNotes: ["Vetiver", "Musk", "Patchouli"],
    occasion: "Daytime",
    season: "Spring",
    sillage: "Moderate",
    story: "A timeless modern gentleman\u2019s fragrance with crisp citrus, soft leather and a smooth woody base for everyday luxury.",
    howToWear: "Spray to the wrists and collar for a polished, confidence-boosting trail.",
    whenToWear: "Perfect for daywear, office appointments and weekend gatherings.",
    longevity: "7\u20139 hours",
    projection: "Moderate",
    size: "100 ml",
    price: 169,
    oldPrice: 199,
    discount: "15%",
    stock: 18,
    rating: 4.7,
    reviewCount: 92,
    featured: false,
    bestseller: true,
    delivery: "Fast delivery across the UAE.",
    notes: ["Crisp citrus", "Soft leather"],
    images: [3, 4, 5],
    image360: 3
  }),
  createProduct({
    slug: "polo-50-ml",
    name: "Polo (50 ml)",
    category: "Eau de Parfum",
    gender: "Men",
    fragranceFamily: "Woody",
    topNotes: ["Lemon", "Sage", "Blackcurrant"],
    heartNotes: ["Leather", "Cedarwood", "Ambergris"],
    baseNotes: ["Vetiver", "Musk", "Patchouli"],
    occasion: "Daytime",
    season: "Spring",
    sillage: "Moderate",
    story: "A timeless modern gentleman\u2019s fragrance with crisp citrus, soft leather and a smooth woody base for everyday luxury.",
    howToWear: "Spray to the wrists and collar for a polished, confidence-boosting trail.",
    whenToWear: "Perfect for daywear, office appointments and weekend gatherings.",
    longevity: "7\u20139 hours",
    projection: "Moderate",
    size: "50 ml",
    price: 127,
    oldPrice: 149,
    discount: "15%",
    stock: 16,
    rating: 4.7,
    reviewCount: 69,
    featured: false,
    bestseller: false,
    delivery: "Fast delivery across the UAE.",
    notes: ["Crisp citrus", "Soft leather"],
    images: [3, 4, 5],
    image360: 3,
    reviews: [],
    questions: []
  }),
  createProduct({
    slug: "polo-travel-duo",
    name: "Polo (Travel Duo)",
    category: "Eau de Parfum",
    gender: "Men",
    fragranceFamily: "Woody",
    topNotes: ["Lemon", "Sage", "Blackcurrant"],
    heartNotes: ["Leather", "Cedarwood", "Ambergris"],
    baseNotes: ["Vetiver", "Musk", "Patchouli"],
    occasion: "Daytime",
    season: "Spring",
    sillage: "Moderate",
    story: "A timeless modern gentleman\u2019s fragrance with crisp citrus, soft leather and a smooth woody base for everyday luxury.",
    howToWear: "Spray to the wrists and collar for a polished, confidence-boosting trail.",
    whenToWear: "Perfect for daywear, office appointments and weekend gatherings.",
    longevity: "7\u20139 hours",
    projection: "Moderate",
    size: "Travel Duo",
    price: 152,
    oldPrice: 179,
    discount: "15%",
    stock: 16,
    rating: 4.7,
    reviewCount: 82,
    featured: false,
    bestseller: false,
    delivery: "Fast delivery across the UAE.",
    notes: ["Crisp citrus", "Soft leather"],
    images: [3, 4, 5],
    image360: 3,
    reviews: [],
    questions: []
  }),
  createProduct({
    slug: "polo-gift-set",
    name: "Polo (Gift Set)",
    category: "Eau de Parfum",
    gender: "Men",
    fragranceFamily: "Woody",
    topNotes: ["Lemon", "Sage", "Blackcurrant"],
    heartNotes: ["Leather", "Cedarwood", "Ambergris"],
    baseNotes: ["Vetiver", "Musk", "Patchouli"],
    occasion: "Daytime",
    season: "Spring",
    sillage: "Moderate",
    story: "A timeless modern gentleman\u2019s fragrance with crisp citrus, soft leather and a smooth woody base for everyday luxury.",
    howToWear: "Spray to the wrists and collar for a polished, confidence-boosting trail.",
    whenToWear: "Perfect for daywear, office appointments and weekend gatherings.",
    longevity: "7\u20139 hours",
    projection: "Moderate",
    size: "Gift Set",
    price: 203,
    oldPrice: 239,
    discount: "15%",
    stock: 16,
    rating: 4.7,
    reviewCount: 110,
    featured: false,
    bestseller: false,
    delivery: "Fast delivery across the UAE.",
    notes: ["Crisp citrus", "Soft leather"],
    images: [3, 4, 5],
    image360: 3,
    reviews: [],
    questions: []
  }),
  createProduct({
    slug: "polo-travel-trio",
    name: "Polo (Travel Trio)",
    category: "Eau de Parfum",
    gender: "Men",
    fragranceFamily: "Woody",
    topNotes: ["Lemon", "Sage", "Blackcurrant"],
    heartNotes: ["Leather", "Cedarwood", "Ambergris"],
    baseNotes: ["Vetiver", "Musk", "Patchouli"],
    occasion: "Daytime",
    season: "Spring",
    sillage: "Moderate",
    story: "A timeless modern gentleman\u2019s fragrance with crisp citrus, soft leather and a smooth woody base for everyday luxury.",
    howToWear: "Spray to the wrists and collar for a polished, confidence-boosting trail.",
    whenToWear: "Perfect for daywear, office appointments and weekend gatherings.",
    longevity: "7\u20139 hours",
    projection: "Moderate",
    size: "Travel Trio",
    price: 144,
    oldPrice: 169,
    discount: "15%",
    stock: 16,
    rating: 4.7,
    reviewCount: 78,
    featured: false,
    bestseller: false,
    delivery: "Fast delivery across the UAE.",
    notes: ["Crisp citrus", "Soft leather"],
    images: [3, 4, 5],
    image360: 3,
    reviews: [],
    questions: []
  }),
  createProduct({
    slug: "hhh",
    name: "HHH",
    category: "Eau de Parfum",
    gender: "Unisex",
    fragranceFamily: "Amber",
    topNotes: ["Saffron", "Oud", "Cardamom"],
    heartNotes: ["Amberwood", "Jasmine", "Rose"],
    baseNotes: ["Leather", "Musk", "Vanilla"],
    occasion: "Evening",
    season: "Winter",
    sillage: "Strong",
    story: "An intimate rich fragrance with spicy intensity and a luxurious amber trail designed for the modern oud lover.",
    howToWear: "Apply to pulse points and allow the scent to mature into a warm, elegant finish.",
    whenToWear: "Ideal for dramatic evenings, formal events and candlelit nights.",
    longevity: "10+ hours",
    projection: "Strong",
    size: "100 ml",
    price: 289,
    oldPrice: 339,
    discount: "15%",
    stock: 12,
    rating: 4.8,
    reviewCount: 81,
    featured: true,
    bestseller: false,
    delivery: "Premium shipping included.",
    notes: ["Spicy saffron", "Amber richness"],
    images: [4, 5, 6],
    image360: 4
  }),
  createProduct({
    slug: "hhh-50-ml",
    name: "HHH (50 ml)",
    category: "Eau de Parfum",
    gender: "Unisex",
    fragranceFamily: "Amber",
    topNotes: ["Saffron", "Oud", "Cardamom"],
    heartNotes: ["Amberwood", "Jasmine", "Rose"],
    baseNotes: ["Leather", "Musk", "Vanilla"],
    occasion: "Evening",
    season: "Winter",
    sillage: "Strong",
    story: "An intimate rich fragrance with spicy intensity and a luxurious amber trail designed for the modern oud lover.",
    howToWear: "Apply to pulse points and allow the scent to mature into a warm, elegant finish.",
    whenToWear: "Ideal for dramatic evenings, formal events and candlelit nights.",
    longevity: "10+ hours",
    projection: "Strong",
    size: "50 ml",
    price: 217,
    oldPrice: 254,
    discount: "15%",
    stock: 10,
    rating: 4.8,
    reviewCount: 60,
    featured: false,
    bestseller: false,
    delivery: "Premium shipping included.",
    notes: ["Spicy saffron", "Amber richness"],
    images: [4, 5, 6],
    image360: 4,
    reviews: [],
    questions: []
  }),
  createProduct({
    slug: "hhh-travel-duo",
    name: "HHH (Travel Duo)",
    category: "Eau de Parfum",
    gender: "Unisex",
    fragranceFamily: "Amber",
    topNotes: ["Saffron", "Oud", "Cardamom"],
    heartNotes: ["Amberwood", "Jasmine", "Rose"],
    baseNotes: ["Leather", "Musk", "Vanilla"],
    occasion: "Evening",
    season: "Winter",
    sillage: "Strong",
    story: "An intimate rich fragrance with spicy intensity and a luxurious amber trail designed for the modern oud lover.",
    howToWear: "Apply to pulse points and allow the scent to mature into a warm, elegant finish.",
    whenToWear: "Ideal for dramatic evenings, formal events and candlelit nights.",
    longevity: "10+ hours",
    projection: "Strong",
    size: "Travel Duo",
    price: 260,
    oldPrice: 305,
    discount: "15%",
    stock: 10,
    rating: 4.8,
    reviewCount: 72,
    featured: false,
    bestseller: false,
    delivery: "Premium shipping included.",
    notes: ["Spicy saffron", "Amber richness"],
    images: [4, 5, 6],
    image360: 4,
    reviews: [],
    questions: []
  }),
  createProduct({
    slug: "hhh-gift-set",
    name: "HHH (Gift Set)",
    category: "Eau de Parfum",
    gender: "Unisex",
    fragranceFamily: "Amber",
    topNotes: ["Saffron", "Oud", "Cardamom"],
    heartNotes: ["Amberwood", "Jasmine", "Rose"],
    baseNotes: ["Leather", "Musk", "Vanilla"],
    occasion: "Evening",
    season: "Winter",
    sillage: "Strong",
    story: "An intimate rich fragrance with spicy intensity and a luxurious amber trail designed for the modern oud lover.",
    howToWear: "Apply to pulse points and allow the scent to mature into a warm, elegant finish.",
    whenToWear: "Ideal for dramatic evenings, formal events and candlelit nights.",
    longevity: "10+ hours",
    projection: "Strong",
    size: "Gift Set",
    price: 347,
    oldPrice: 407,
    discount: "15%",
    stock: 10,
    rating: 4.8,
    reviewCount: 97,
    featured: false,
    bestseller: false,
    delivery: "Premium shipping included.",
    notes: ["Spicy saffron", "Amber richness"],
    images: [4, 5, 6],
    image360: 4,
    reviews: [],
    questions: []
  }),
  createProduct({
    slug: "hhh-travel-trio",
    name: "HHH (Travel Trio)",
    category: "Eau de Parfum",
    gender: "Unisex",
    fragranceFamily: "Amber",
    topNotes: ["Saffron", "Oud", "Cardamom"],
    heartNotes: ["Amberwood", "Jasmine", "Rose"],
    baseNotes: ["Leather", "Musk", "Vanilla"],
    occasion: "Evening",
    season: "Winter",
    sillage: "Strong",
    story: "An intimate rich fragrance with spicy intensity and a luxurious amber trail designed for the modern oud lover.",
    howToWear: "Apply to pulse points and allow the scent to mature into a warm, elegant finish.",
    whenToWear: "Ideal for dramatic evenings, formal events and candlelit nights.",
    longevity: "10+ hours",
    projection: "Strong",
    size: "Travel Trio",
    price: 246,
    oldPrice: 288,
    discount: "15%",
    stock: 10,
    rating: 4.8,
    reviewCount: 68,
    featured: false,
    bestseller: false,
    delivery: "Premium shipping included.",
    notes: ["Spicy saffron", "Amber richness"],
    images: [4, 5, 6],
    image360: 4,
    reviews: [],
    questions: []
  }),
  createProduct({
    slug: "dove",
    name: "Dove",
    category: "Eau de Parfum",
    gender: "Women",
    fragranceFamily: "Floral",
    topNotes: ["Lily", "Jasmine", "Bergamot"],
    heartNotes: ["Almond", "Vanilla", "Rose"],
    baseNotes: ["Musk", "Amber", "Sandalwood"],
    occasion: "Daytime",
    season: "Spring",
    sillage: "Moderate",
    story: "A soft floral fragrance with comforting warmth and a delicate plush finish that feels like a luxurious embrace.",
    howToWear: "Mist lightly to the neck and behind ears for a tender floral glow.",
    whenToWear: "Ideal for daytime gatherings, romantic lunches and refined occasions.",
    longevity: "7\u20138 hours",
    projection: "Moderate",
    size: "100 ml",
    price: 139,
    oldPrice: 169,
    discount: "18%",
    stock: 15,
    rating: 4.7,
    reviewCount: 74,
    featured: false,
    bestseller: true,
    delivery: "Gift-ready packaging with every order.",
    notes: ["Creamy florals", "Soft musk"],
    images: [5, 6, 7],
    image360: 5
  }),
  createProduct({
    slug: "dove-50-ml",
    name: "Dove (50 ml)",
    category: "Eau de Parfum",
    gender: "Women",
    fragranceFamily: "Floral",
    topNotes: ["Lily", "Jasmine", "Bergamot"],
    heartNotes: ["Almond", "Vanilla", "Rose"],
    baseNotes: ["Musk", "Amber", "Sandalwood"],
    occasion: "Daytime",
    season: "Spring",
    sillage: "Moderate",
    story: "A soft floral fragrance with comforting warmth and a delicate plush finish that feels like a luxurious embrace.",
    howToWear: "Mist lightly to the neck and behind ears for a tender floral glow.",
    whenToWear: "Ideal for daytime gatherings, romantic lunches and refined occasions.",
    longevity: "7\u20138 hours",
    projection: "Moderate",
    size: "50 ml",
    price: 104,
    oldPrice: 127,
    discount: "18%",
    stock: 13,
    rating: 4.7,
    reviewCount: 55,
    featured: false,
    bestseller: false,
    delivery: "Gift-ready packaging with every order.",
    notes: ["Creamy florals", "Soft musk"],
    images: [5, 6, 7],
    image360: 5,
    reviews: [],
    questions: []
  }),
  createProduct({
    slug: "dove-travel-duo",
    name: "Dove (Travel Duo)",
    category: "Eau de Parfum",
    gender: "Women",
    fragranceFamily: "Floral",
    topNotes: ["Lily", "Jasmine", "Bergamot"],
    heartNotes: ["Almond", "Vanilla", "Rose"],
    baseNotes: ["Musk", "Amber", "Sandalwood"],
    occasion: "Daytime",
    season: "Spring",
    sillage: "Moderate",
    story: "A soft floral fragrance with comforting warmth and a delicate plush finish that feels like a luxurious embrace.",
    howToWear: "Mist lightly to the neck and behind ears for a tender floral glow.",
    whenToWear: "Ideal for daytime gatherings, romantic lunches and refined occasions.",
    longevity: "7\u20138 hours",
    projection: "Moderate",
    size: "Travel Duo",
    price: 125,
    oldPrice: 152,
    discount: "18%",
    stock: 13,
    rating: 4.7,
    reviewCount: 66,
    featured: false,
    bestseller: false,
    delivery: "Gift-ready packaging with every order.",
    notes: ["Creamy florals", "Soft musk"],
    images: [5, 6, 7],
    image360: 5,
    reviews: [],
    questions: []
  }),
  createProduct({
    slug: "dove-gift-set",
    name: "Dove (Gift Set)",
    category: "Eau de Parfum",
    gender: "Women",
    fragranceFamily: "Floral",
    topNotes: ["Lily", "Jasmine", "Bergamot"],
    heartNotes: ["Almond", "Vanilla", "Rose"],
    baseNotes: ["Musk", "Amber", "Sandalwood"],
    occasion: "Daytime",
    season: "Spring",
    sillage: "Moderate",
    story: "A soft floral fragrance with comforting warmth and a delicate plush finish that feels like a luxurious embrace.",
    howToWear: "Mist lightly to the neck and behind ears for a tender floral glow.",
    whenToWear: "Ideal for daytime gatherings, romantic lunches and refined occasions.",
    longevity: "7\u20138 hours",
    projection: "Moderate",
    size: "Gift Set",
    price: 167,
    oldPrice: 203,
    discount: "18%",
    stock: 13,
    rating: 4.7,
    reviewCount: 88,
    featured: false,
    bestseller: false,
    delivery: "Gift-ready packaging with every order.",
    notes: ["Creamy florals", "Soft musk"],
    images: [5, 6, 7],
    image360: 5,
    reviews: [],
    questions: []
  }),
  createProduct({
    slug: "dove-travel-trio",
    name: "Dove (Travel Trio)",
    category: "Eau de Parfum",
    gender: "Women",
    fragranceFamily: "Floral",
    topNotes: ["Lily", "Jasmine", "Bergamot"],
    heartNotes: ["Almond", "Vanilla", "Rose"],
    baseNotes: ["Musk", "Amber", "Sandalwood"],
    occasion: "Daytime",
    season: "Spring",
    sillage: "Moderate",
    story: "A soft floral fragrance with comforting warmth and a delicate plush finish that feels like a luxurious embrace.",
    howToWear: "Mist lightly to the neck and behind ears for a tender floral glow.",
    whenToWear: "Ideal for daytime gatherings, romantic lunches and refined occasions.",
    longevity: "7\u20138 hours",
    projection: "Moderate",
    size: "Travel Trio",
    price: 118,
    oldPrice: 144,
    discount: "18%",
    stock: 13,
    rating: 4.7,
    reviewCount: 62,
    featured: false,
    bestseller: false,
    delivery: "Gift-ready packaging with every order.",
    notes: ["Creamy florals", "Soft musk"],
    images: [5, 6, 7],
    image360: 5,
    reviews: [],
    questions: []
  }),
  createProduct({
    slug: "kashmiri-oud",
    name: "Kashmiri Oud",
    category: "Attars",
    gender: "Unisex",
    fragranceFamily: "Oud",
    topNotes: ["Saffron", "Amber", "Bergamot"],
    heartNotes: ["Oud", "Rose", "Incense"],
    baseNotes: ["Sandalwood", "Vanilla", "Musk"],
    occasion: "Evening",
    season: "Winter",
    sillage: "Moderate",
    story: "A luxurious attar anchored by noble oud and rich amber, recalling traditional Kashmiri warmth and modern refinement.",
    howToWear: "Apply a small amount to pulse points for a long wearing oud veil.",
    whenToWear: "Perfect for formal evenings, festive gatherings and refined rituals.",
    longevity: "10+ hours",
    projection: "Moderate",
    size: "12 ml",
    price: 159,
    oldPrice: 189,
    discount: "16%",
    stock: 22,
    rating: 4.9,
    reviewCount: 105,
    featured: true,
    bestseller: true,
    delivery: "Hand-crafted presentation included.",
    notes: ["Noble oud", "Golden amber"],
    images: [6, 7, 8],
    image360: 6
  }),
  createProduct({
    slug: "kashmiri-oud-100-ml",
    name: "Kashmiri Oud (100 ml)",
    category: "Attars",
    gender: "Unisex",
    fragranceFamily: "Oud",
    topNotes: ["Saffron", "Amber", "Bergamot"],
    heartNotes: ["Oud", "Rose", "Incense"],
    baseNotes: ["Sandalwood", "Vanilla", "Musk"],
    occasion: "Evening",
    season: "Winter",
    sillage: "Moderate",
    story: "A luxurious attar anchored by noble oud and rich amber, recalling traditional Kashmiri warmth and modern refinement.",
    howToWear: "Apply a small amount to pulse points for a long wearing oud veil.",
    whenToWear: "Perfect for formal evenings, festive gatherings and refined rituals.",
    longevity: "10+ hours",
    projection: "Moderate",
    size: "100 ml",
    price: 159,
    oldPrice: 189,
    discount: "16%",
    stock: 20,
    rating: 4.9,
    reviewCount: 105,
    featured: false,
    bestseller: false,
    delivery: "Hand-crafted presentation included.",
    notes: ["Noble oud", "Golden amber"],
    images: [6, 7, 8],
    image360: 6,
    reviews: [],
    questions: []
  }),
  createProduct({
    slug: "kashmiri-oud-50-ml",
    name: "Kashmiri Oud (50 ml)",
    category: "Attars",
    gender: "Unisex",
    fragranceFamily: "Oud",
    topNotes: ["Saffron", "Amber", "Bergamot"],
    heartNotes: ["Oud", "Rose", "Incense"],
    baseNotes: ["Sandalwood", "Vanilla", "Musk"],
    occasion: "Evening",
    season: "Winter",
    sillage: "Moderate",
    story: "A luxurious attar anchored by noble oud and rich amber, recalling traditional Kashmiri warmth and modern refinement.",
    howToWear: "Apply a small amount to pulse points for a long wearing oud veil.",
    whenToWear: "Perfect for formal evenings, festive gatherings and refined rituals.",
    longevity: "10+ hours",
    projection: "Moderate",
    size: "50 ml",
    price: 119,
    oldPrice: 142,
    discount: "16%",
    stock: 20,
    rating: 4.9,
    reviewCount: 78,
    featured: false,
    bestseller: false,
    delivery: "Hand-crafted presentation included.",
    notes: ["Noble oud", "Golden amber"],
    images: [6, 7, 8],
    image360: 6,
    reviews: [],
    questions: []
  }),
  createProduct({
    slug: "kashmiri-oud-travel-duo",
    name: "Kashmiri Oud (Travel Duo)",
    category: "Attars",
    gender: "Unisex",
    fragranceFamily: "Oud",
    topNotes: ["Saffron", "Amber", "Bergamot"],
    heartNotes: ["Oud", "Rose", "Incense"],
    baseNotes: ["Sandalwood", "Vanilla", "Musk"],
    occasion: "Evening",
    season: "Winter",
    sillage: "Moderate",
    story: "A luxurious attar anchored by noble oud and rich amber, recalling traditional Kashmiri warmth and modern refinement.",
    howToWear: "Apply a small amount to pulse points for a long wearing oud veil.",
    whenToWear: "Perfect for formal evenings, festive gatherings and refined rituals.",
    longevity: "10+ hours",
    projection: "Moderate",
    size: "Travel Duo",
    price: 143,
    oldPrice: 170,
    discount: "16%",
    stock: 20,
    rating: 4.9,
    reviewCount: 94,
    featured: false,
    bestseller: false,
    delivery: "Hand-crafted presentation included.",
    notes: ["Noble oud", "Golden amber"],
    images: [6, 7, 8],
    image360: 6,
    reviews: [],
    questions: []
  }),
  createProduct({
    slug: "kashmiri-oud-attar-12-ml",
    name: "Kashmiri Oud (Attar 12 ml)",
    category: "Attars",
    gender: "Unisex",
    fragranceFamily: "Oud",
    topNotes: ["Saffron", "Amber", "Bergamot"],
    heartNotes: ["Oud", "Rose", "Incense"],
    baseNotes: ["Sandalwood", "Vanilla", "Musk"],
    occasion: "Evening",
    season: "Winter",
    sillage: "Moderate",
    story: "A luxurious attar anchored by noble oud and rich amber, recalling traditional Kashmiri warmth and modern refinement.",
    howToWear: "Apply a small amount to pulse points for a long wearing oud veil.",
    whenToWear: "Perfect for formal evenings, festive gatherings and refined rituals.",
    longevity: "10+ hours",
    projection: "Moderate",
    size: "Attar 12 ml",
    price: 95,
    oldPrice: 113,
    discount: "16%",
    stock: 20,
    rating: 4.9,
    reviewCount: 63,
    featured: false,
    bestseller: false,
    delivery: "Hand-crafted presentation included.",
    notes: ["Noble oud", "Golden amber"],
    images: [6, 7, 8],
    image360: 6,
    reviews: [],
    questions: []
  }),
  createProduct({
    slug: "kashmiri-oud-travel-trio",
    name: "Kashmiri Oud (Travel Trio)",
    category: "Attars",
    gender: "Unisex",
    fragranceFamily: "Oud",
    topNotes: ["Saffron", "Amber", "Bergamot"],
    heartNotes: ["Oud", "Rose", "Incense"],
    baseNotes: ["Sandalwood", "Vanilla", "Musk"],
    occasion: "Evening",
    season: "Winter",
    sillage: "Moderate",
    story: "A luxurious attar anchored by noble oud and rich amber, recalling traditional Kashmiri warmth and modern refinement.",
    howToWear: "Apply a small amount to pulse points for a long wearing oud veil.",
    whenToWear: "Perfect for formal evenings, festive gatherings and refined rituals.",
    longevity: "10+ hours",
    projection: "Moderate",
    size: "Travel Trio",
    price: 135,
    oldPrice: 161,
    discount: "16%",
    stock: 20,
    rating: 4.9,
    reviewCount: 89,
    featured: false,
    bestseller: false,
    delivery: "Hand-crafted presentation included.",
    notes: ["Noble oud", "Golden amber"],
    images: [6, 7, 8],
    image360: 6,
    reviews: [],
    questions: []
  }),
  createProduct({
    slug: "bombay-oud",
    name: "Bombay Oud",
    category: "Luxury Collection",
    gender: "Unisex",
    fragranceFamily: "Woody",
    topNotes: ["Cardamom", "Black Pepper", "Lime"],
    heartNotes: ["Oud", "Incense", "Leather"],
    baseNotes: ["Amber", "Cedarwood", "Musk"],
    occasion: "Evening",
    season: "Autumn",
    sillage: "Strong",
    story: "A bold oriental woody composition that blends modern charisma with a warm smoky finish, inspired by the spirit of Bombay.",
    howToWear: "Apply to pulse points for an intense and long-lasting trail.",
    whenToWear: "Great for autumn evenings, formal events and luxury dinners.",
    longevity: "10+ hours",
    projection: "Strong",
    size: "100 ml",
    price: 249,
    oldPrice: 289,
    discount: "14%",
    stock: 11,
    rating: 4.8,
    reviewCount: 90,
    featured: false,
    bestseller: true,
    delivery: "Luxury packaging included.",
    notes: ["Smoky woods", "Vivid spice"],
    images: [7, 8, 9],
    image360: 7
  }),
  createProduct({
    slug: "bombay-oud-50-ml",
    name: "Bombay Oud (50 ml)",
    category: "Luxury Collection",
    gender: "Unisex",
    fragranceFamily: "Woody",
    topNotes: ["Cardamom", "Black Pepper", "Lime"],
    heartNotes: ["Oud", "Incense", "Leather"],
    baseNotes: ["Amber", "Cedarwood", "Musk"],
    occasion: "Evening",
    season: "Autumn",
    sillage: "Strong",
    story: "A bold oriental woody composition that blends modern charisma with a warm smoky finish, inspired by the spirit of Bombay.",
    howToWear: "Apply to pulse points for an intense and long-lasting trail.",
    whenToWear: "Great for autumn evenings, formal events and luxury dinners.",
    longevity: "10+ hours",
    projection: "Strong",
    size: "50 ml",
    price: 187,
    oldPrice: 217,
    discount: "14%",
    stock: 9,
    rating: 4.8,
    reviewCount: 67,
    featured: false,
    bestseller: false,
    delivery: "Luxury packaging included.",
    notes: ["Smoky woods", "Vivid spice"],
    images: [7, 8, 9],
    image360: 7,
    reviews: [],
    questions: []
  }),
  createProduct({
    slug: "bombay-oud-travel-duo",
    name: "Bombay Oud (Travel Duo)",
    category: "Luxury Collection",
    gender: "Unisex",
    fragranceFamily: "Woody",
    topNotes: ["Cardamom", "Black Pepper", "Lime"],
    heartNotes: ["Oud", "Incense", "Leather"],
    baseNotes: ["Amber", "Cedarwood", "Musk"],
    occasion: "Evening",
    season: "Autumn",
    sillage: "Strong",
    story: "A bold oriental woody composition that blends modern charisma with a warm smoky finish, inspired by the spirit of Bombay.",
    howToWear: "Apply to pulse points for an intense and long-lasting trail.",
    whenToWear: "Great for autumn evenings, formal events and luxury dinners.",
    longevity: "10+ hours",
    projection: "Strong",
    size: "Travel Duo",
    price: 224,
    oldPrice: 260,
    discount: "14%",
    stock: 9,
    rating: 4.8,
    reviewCount: 81,
    featured: false,
    bestseller: false,
    delivery: "Luxury packaging included.",
    notes: ["Smoky woods", "Vivid spice"],
    images: [7, 8, 9],
    image360: 7,
    reviews: [],
    questions: []
  }),
  createProduct({
    slug: "bombay-oud-gift-set",
    name: "Bombay Oud (Gift Set)",
    category: "Luxury Collection",
    gender: "Unisex",
    fragranceFamily: "Woody",
    topNotes: ["Cardamom", "Black Pepper", "Lime"],
    heartNotes: ["Oud", "Incense", "Leather"],
    baseNotes: ["Amber", "Cedarwood", "Musk"],
    occasion: "Evening",
    season: "Autumn",
    sillage: "Strong",
    story: "A bold oriental woody composition that blends modern charisma with a warm smoky finish, inspired by the spirit of Bombay.",
    howToWear: "Apply to pulse points for an intense and long-lasting trail.",
    whenToWear: "Great for autumn evenings, formal events and luxury dinners.",
    longevity: "10+ hours",
    projection: "Strong",
    size: "Gift Set",
    price: 299,
    oldPrice: 347,
    discount: "14%",
    stock: 9,
    rating: 4.8,
    reviewCount: 108,
    featured: false,
    bestseller: false,
    delivery: "Luxury packaging included.",
    notes: ["Smoky woods", "Vivid spice"],
    images: [7, 8, 9],
    image360: 7,
    reviews: [],
    questions: []
  }),
  createProduct({
    slug: "bombay-oud-travel-trio",
    name: "Bombay Oud (Travel Trio)",
    category: "Luxury Collection",
    gender: "Unisex",
    fragranceFamily: "Woody",
    topNotes: ["Cardamom", "Black Pepper", "Lime"],
    heartNotes: ["Oud", "Incense", "Leather"],
    baseNotes: ["Amber", "Cedarwood", "Musk"],
    occasion: "Evening",
    season: "Autumn",
    sillage: "Strong",
    story: "A bold oriental woody composition that blends modern charisma with a warm smoky finish, inspired by the spirit of Bombay.",
    howToWear: "Apply to pulse points for an intense and long-lasting trail.",
    whenToWear: "Great for autumn evenings, formal events and luxury dinners.",
    longevity: "10+ hours",
    projection: "Strong",
    size: "Travel Trio",
    price: 212,
    oldPrice: 246,
    discount: "14%",
    stock: 9,
    rating: 4.8,
    reviewCount: 76,
    featured: false,
    bestseller: false,
    delivery: "Luxury packaging included.",
    notes: ["Smoky woods", "Vivid spice"],
    images: [7, 8, 9],
    image360: 7,
    reviews: [],
    questions: []
  }),
  createProduct({
    slug: "chocolate",
    name: "Chocolate",
    category: "Eau de Parfum",
    gender: "Unisex",
    fragranceFamily: "Amber",
    topNotes: ["Cocoa", "Orange", "Tonka Bean"],
    heartNotes: ["Chocolate", "Rose", "Vanilla"],
    baseNotes: ["Oud", "Caramel", "Patchouli"],
    occasion: "Evening",
    season: "Winter",
    sillage: "Moderate",
    story: "A decadent gourmand fragrance with rich chocolate and warm resinous depth that feels indulgent and comforting.",
    howToWear: "Apply generously to pulse points for a delicious velvety finish.",
    whenToWear: "Perfect for colder nights, celebrations and elegant evenings.",
    longevity: "9\u201311 hours",
    projection: "Moderate",
    size: "100 ml",
    price: 189,
    oldPrice: 219,
    discount: "14%",
    stock: 13,
    rating: 4.7,
    reviewCount: 78,
    featured: false,
    bestseller: false,
    delivery: "Complimentary sample included.",
    notes: ["Rich cocoa", "Creamy vanilla"],
    images: [8, 9, 1],
    image360: 8
  }),
  createProduct({
    slug: "chocolate-50-ml",
    name: "Chocolate (50 ml)",
    category: "Eau de Parfum",
    gender: "Unisex",
    fragranceFamily: "Amber",
    topNotes: ["Cocoa", "Orange", "Tonka Bean"],
    heartNotes: ["Chocolate", "Rose", "Vanilla"],
    baseNotes: ["Oud", "Caramel", "Patchouli"],
    occasion: "Evening",
    season: "Winter",
    sillage: "Moderate",
    story: "A decadent gourmand fragrance with rich chocolate and warm resinous depth that feels indulgent and comforting.",
    howToWear: "Apply generously to pulse points for a delicious velvety finish.",
    whenToWear: "Perfect for colder nights, celebrations and elegant evenings.",
    longevity: "9\u201311 hours",
    projection: "Moderate",
    size: "50 ml",
    price: 142,
    oldPrice: 164,
    discount: "13%",
    stock: 11,
    rating: 4.7,
    reviewCount: 58,
    featured: false,
    bestseller: false,
    delivery: "Complimentary sample included.",
    notes: ["Rich cocoa", "Creamy vanilla"],
    images: [8, 9, 1],
    image360: 8,
    reviews: [],
    questions: []
  }),
  createProduct({
    slug: "chocolate-travel-duo",
    name: "Chocolate (Travel Duo)",
    category: "Eau de Parfum",
    gender: "Unisex",
    fragranceFamily: "Amber",
    topNotes: ["Cocoa", "Orange", "Tonka Bean"],
    heartNotes: ["Chocolate", "Rose", "Vanilla"],
    baseNotes: ["Oud", "Caramel", "Patchouli"],
    occasion: "Evening",
    season: "Winter",
    sillage: "Moderate",
    story: "A decadent gourmand fragrance with rich chocolate and warm resinous depth that feels indulgent and comforting.",
    howToWear: "Apply generously to pulse points for a delicious velvety finish.",
    whenToWear: "Perfect for colder nights, celebrations and elegant evenings.",
    longevity: "9\u201311 hours",
    projection: "Moderate",
    size: "Travel Duo",
    price: 170,
    oldPrice: 197,
    discount: "14%",
    stock: 11,
    rating: 4.7,
    reviewCount: 70,
    featured: false,
    bestseller: false,
    delivery: "Complimentary sample included.",
    notes: ["Rich cocoa", "Creamy vanilla"],
    images: [8, 9, 1],
    image360: 8,
    reviews: [],
    questions: []
  }),
  createProduct({
    slug: "chocolate-gift-set",
    name: "Chocolate (Gift Set)",
    category: "Eau de Parfum",
    gender: "Unisex",
    fragranceFamily: "Amber",
    topNotes: ["Cocoa", "Orange", "Tonka Bean"],
    heartNotes: ["Chocolate", "Rose", "Vanilla"],
    baseNotes: ["Oud", "Caramel", "Patchouli"],
    occasion: "Evening",
    season: "Winter",
    sillage: "Moderate",
    story: "A decadent gourmand fragrance with rich chocolate and warm resinous depth that feels indulgent and comforting.",
    howToWear: "Apply generously to pulse points for a delicious velvety finish.",
    whenToWear: "Perfect for colder nights, celebrations and elegant evenings.",
    longevity: "9\u201311 hours",
    projection: "Moderate",
    size: "Gift Set",
    price: 227,
    oldPrice: 263,
    discount: "14%",
    stock: 11,
    rating: 4.7,
    reviewCount: 93,
    featured: false,
    bestseller: false,
    delivery: "Complimentary sample included.",
    notes: ["Rich cocoa", "Creamy vanilla"],
    images: [8, 9, 1],
    image360: 8,
    reviews: [],
    questions: []
  }),
  createProduct({
    slug: "chocolate-travel-trio",
    name: "Chocolate (Travel Trio)",
    category: "Eau de Parfum",
    gender: "Unisex",
    fragranceFamily: "Amber",
    topNotes: ["Cocoa", "Orange", "Tonka Bean"],
    heartNotes: ["Chocolate", "Rose", "Vanilla"],
    baseNotes: ["Oud", "Caramel", "Patchouli"],
    occasion: "Evening",
    season: "Winter",
    sillage: "Moderate",
    story: "A decadent gourmand fragrance with rich chocolate and warm resinous depth that feels indulgent and comforting.",
    howToWear: "Apply generously to pulse points for a delicious velvety finish.",
    whenToWear: "Perfect for colder nights, celebrations and elegant evenings.",
    longevity: "9\u201311 hours",
    projection: "Moderate",
    size: "Travel Trio",
    price: 161,
    oldPrice: 186,
    discount: "13%",
    stock: 11,
    rating: 4.7,
    reviewCount: 66,
    featured: false,
    bestseller: false,
    delivery: "Complimentary sample included.",
    notes: ["Rich cocoa", "Creamy vanilla"],
    images: [8, 9, 1],
    image360: 8,
    reviews: [],
    questions: []
  }),
  createProduct({
    slug: "musk-mumtaz",
    name: "Musk Mumtaz",
    category: "Attars",
    gender: "Women",
    fragranceFamily: "Musk",
    topNotes: ["Neroli", "Pear", "Bergamot"],
    heartNotes: ["Musk", "Orchid", "Ambergris"],
    baseNotes: ["Vanilla", "Sandalwood", "Amber"],
    occasion: "Evening",
    season: "All year",
    sillage: "Soft",
    story: "A sophisticated musk attar built around creamy florals and amber depths for a polished, intimate presence.",
    howToWear: "Apply lightly to wrists and behind the ears for an elegant skin scent.",
    whenToWear: "Great for romantic evenings, gifting and special occasions.",
    longevity: "8\u201310 hours",
    projection: "Soft",
    size: "10 ml",
    price: 129,
    oldPrice: 149,
    discount: "13%",
    stock: 16,
    rating: 4.8,
    reviewCount: 84,
    featured: false,
    bestseller: false,
    delivery: "Signature roll-on bottle included.",
    notes: ["Creamy musk", "Floral warmth"],
    images: [9, 1, 2],
    image360: 9
  }),
  createProduct({
    slug: "musk-mumtaz-100-ml",
    name: "Musk Mumtaz (100 ml)",
    category: "Attars",
    gender: "Women",
    fragranceFamily: "Musk",
    topNotes: ["Neroli", "Pear", "Bergamot"],
    heartNotes: ["Musk", "Orchid", "Ambergris"],
    baseNotes: ["Vanilla", "Sandalwood", "Amber"],
    occasion: "Evening",
    season: "All year",
    sillage: "Soft",
    story: "A sophisticated musk attar built around creamy florals and amber depths for a polished, intimate presence.",
    howToWear: "Apply lightly to wrists and behind the ears for an elegant skin scent.",
    whenToWear: "Great for romantic evenings, gifting and special occasions.",
    longevity: "8\u201310 hours",
    projection: "Soft",
    size: "100 ml",
    price: 129,
    oldPrice: 149,
    discount: "13%",
    stock: 14,
    rating: 4.8,
    reviewCount: 84,
    featured: false,
    bestseller: false,
    delivery: "Signature roll-on bottle included.",
    notes: ["Creamy musk", "Floral warmth"],
    images: [9, 1, 2],
    image360: 9,
    reviews: [],
    questions: []
  }),
  createProduct({
    slug: "musk-mumtaz-50-ml",
    name: "Musk Mumtaz (50 ml)",
    category: "Attars",
    gender: "Women",
    fragranceFamily: "Musk",
    topNotes: ["Neroli", "Pear", "Bergamot"],
    heartNotes: ["Musk", "Orchid", "Ambergris"],
    baseNotes: ["Vanilla", "Sandalwood", "Amber"],
    occasion: "Evening",
    season: "All year",
    sillage: "Soft",
    story: "A sophisticated musk attar built around creamy florals and amber depths for a polished, intimate presence.",
    howToWear: "Apply lightly to wrists and behind the ears for an elegant skin scent.",
    whenToWear: "Great for romantic evenings, gifting and special occasions.",
    longevity: "8\u201310 hours",
    projection: "Soft",
    size: "50 ml",
    price: 97,
    oldPrice: 112,
    discount: "13%",
    stock: 14,
    rating: 4.8,
    reviewCount: 63,
    featured: false,
    bestseller: false,
    delivery: "Signature roll-on bottle included.",
    notes: ["Creamy musk", "Floral warmth"],
    images: [9, 1, 2],
    image360: 9,
    reviews: [],
    questions: []
  }),
  createProduct({
    slug: "musk-mumtaz-travel-duo",
    name: "Musk Mumtaz (Travel Duo)",
    category: "Attars",
    gender: "Women",
    fragranceFamily: "Musk",
    topNotes: ["Neroli", "Pear", "Bergamot"],
    heartNotes: ["Musk", "Orchid", "Ambergris"],
    baseNotes: ["Vanilla", "Sandalwood", "Amber"],
    occasion: "Evening",
    season: "All year",
    sillage: "Soft",
    story: "A sophisticated musk attar built around creamy florals and amber depths for a polished, intimate presence.",
    howToWear: "Apply lightly to wrists and behind the ears for an elegant skin scent.",
    whenToWear: "Great for romantic evenings, gifting and special occasions.",
    longevity: "8\u201310 hours",
    projection: "Soft",
    size: "Travel Duo",
    price: 116,
    oldPrice: 134,
    discount: "13%",
    stock: 14,
    rating: 4.8,
    reviewCount: 75,
    featured: false,
    bestseller: false,
    delivery: "Signature roll-on bottle included.",
    notes: ["Creamy musk", "Floral warmth"],
    images: [9, 1, 2],
    image360: 9,
    reviews: [],
    questions: []
  }),
  createProduct({
    slug: "musk-mumtaz-attar-12-ml",
    name: "Musk Mumtaz (Attar 12 ml)",
    category: "Attars",
    gender: "Women",
    fragranceFamily: "Musk",
    topNotes: ["Neroli", "Pear", "Bergamot"],
    heartNotes: ["Musk", "Orchid", "Ambergris"],
    baseNotes: ["Vanilla", "Sandalwood", "Amber"],
    occasion: "Evening",
    season: "All year",
    sillage: "Soft",
    story: "A sophisticated musk attar built around creamy florals and amber depths for a polished, intimate presence.",
    howToWear: "Apply lightly to wrists and behind the ears for an elegant skin scent.",
    whenToWear: "Great for romantic evenings, gifting and special occasions.",
    longevity: "8\u201310 hours",
    projection: "Soft",
    size: "Attar 12 ml",
    price: 80,
    oldPrice: 90,
    discount: "11%",
    stock: 14,
    rating: 4.8,
    reviewCount: 50,
    featured: false,
    bestseller: false,
    delivery: "Signature roll-on bottle included.",
    notes: ["Creamy musk", "Floral warmth"],
    images: [9, 1, 2],
    image360: 9,
    reviews: [],
    questions: []
  }),
  createProduct({
    slug: "musk-mumtaz-travel-trio",
    name: "Musk Mumtaz (Travel Trio)",
    category: "Attars",
    gender: "Women",
    fragranceFamily: "Musk",
    topNotes: ["Neroli", "Pear", "Bergamot"],
    heartNotes: ["Musk", "Orchid", "Ambergris"],
    baseNotes: ["Vanilla", "Sandalwood", "Amber"],
    occasion: "Evening",
    season: "All year",
    sillage: "Soft",
    story: "A sophisticated musk attar built around creamy florals and amber depths for a polished, intimate presence.",
    howToWear: "Apply lightly to wrists and behind the ears for an elegant skin scent.",
    whenToWear: "Great for romantic evenings, gifting and special occasions.",
    longevity: "8\u201310 hours",
    projection: "Soft",
    size: "Travel Trio",
    price: 110,
    oldPrice: 127,
    discount: "13%",
    stock: 14,
    rating: 4.8,
    reviewCount: 71,
    featured: false,
    bestseller: false,
    delivery: "Signature roll-on bottle included.",
    notes: ["Creamy musk", "Floral warmth"],
    images: [9, 1, 2],
    image360: 9,
    reviews: [],
    questions: []
  }),
  createProduct({
    slug: "black-oud",
    name: "Black Oud",
    category: "Luxury Collection",
    gender: "Men",
    fragranceFamily: "Oud",
    topNotes: ["Saffron", "Black Pepper", "Bergamot"],
    heartNotes: ["Oud", "Patchouli", "Cedarwood"],
    baseNotes: ["Leather", "Amber", "Musk"],
    occasion: "Evening",
    season: "Winter",
    sillage: "Strong",
    story: "A commanding oud fragrance with dark spice, leather and amber for a confident, magnetic signature.",
    howToWear: "Spray to pulse points and allow the oud to deepen through the evening.",
    whenToWear: "Ideal for business evenings, gala events and formal nights.",
    longevity: "10+ hours",
    projection: "Strong",
    size: "100 ml",
    price: 299,
    oldPrice: 349,
    discount: "14%",
    stock: 8,
    rating: 4.9,
    reviewCount: 98,
    featured: true,
    bestseller: true,
    delivery: "Gift-ready box included.",
    notes: ["Deep oud", "Leather contrast"],
    images: [1, 2, 3],
    image360: 1
  }),
  createProduct({
    slug: "black-oud-50-ml",
    name: "Black Oud (50 ml)",
    category: "Luxury Collection",
    gender: "Men",
    fragranceFamily: "Oud",
    topNotes: ["Saffron", "Black Pepper", "Bergamot"],
    heartNotes: ["Oud", "Patchouli", "Cedarwood"],
    baseNotes: ["Leather", "Amber", "Musk"],
    occasion: "Evening",
    season: "Winter",
    sillage: "Strong",
    story: "A commanding oud fragrance with dark spice, leather and amber for a confident, magnetic signature.",
    howToWear: "Spray to pulse points and allow the oud to deepen through the evening.",
    whenToWear: "Ideal for business evenings, gala events and formal nights.",
    longevity: "10+ hours",
    projection: "Strong",
    size: "50 ml",
    price: 224,
    oldPrice: 262,
    discount: "15%",
    stock: 6,
    rating: 4.9,
    reviewCount: 73,
    featured: false,
    bestseller: false,
    delivery: "Gift-ready box included.",
    notes: ["Deep oud", "Leather contrast"],
    images: [1, 2, 3],
    image360: 1,
    reviews: [],
    questions: []
  }),
  createProduct({
    slug: "black-oud-travel-duo",
    name: "Black Oud (Travel Duo)",
    category: "Luxury Collection",
    gender: "Men",
    fragranceFamily: "Oud",
    topNotes: ["Saffron", "Black Pepper", "Bergamot"],
    heartNotes: ["Oud", "Patchouli", "Cedarwood"],
    baseNotes: ["Leather", "Amber", "Musk"],
    occasion: "Evening",
    season: "Winter",
    sillage: "Strong",
    story: "A commanding oud fragrance with dark spice, leather and amber for a confident, magnetic signature.",
    howToWear: "Spray to pulse points and allow the oud to deepen through the evening.",
    whenToWear: "Ideal for business evenings, gala events and formal nights.",
    longevity: "10+ hours",
    projection: "Strong",
    size: "Travel Duo",
    price: 269,
    oldPrice: 314,
    discount: "14%",
    stock: 6,
    rating: 4.9,
    reviewCount: 88,
    featured: false,
    bestseller: false,
    delivery: "Gift-ready box included.",
    notes: ["Deep oud", "Leather contrast"],
    images: [1, 2, 3],
    image360: 1,
    reviews: [],
    questions: []
  }),
  createProduct({
    slug: "black-oud-gift-set",
    name: "Black Oud (Gift Set)",
    category: "Luxury Collection",
    gender: "Men",
    fragranceFamily: "Oud",
    topNotes: ["Saffron", "Black Pepper", "Bergamot"],
    heartNotes: ["Oud", "Patchouli", "Cedarwood"],
    baseNotes: ["Leather", "Amber", "Musk"],
    occasion: "Evening",
    season: "Winter",
    sillage: "Strong",
    story: "A commanding oud fragrance with dark spice, leather and amber for a confident, magnetic signature.",
    howToWear: "Spray to pulse points and allow the oud to deepen through the evening.",
    whenToWear: "Ideal for business evenings, gala events and formal nights.",
    longevity: "10+ hours",
    projection: "Strong",
    size: "Gift Set",
    price: 350,
    oldPrice: 419,
    discount: "16%",
    stock: 6,
    rating: 4.9,
    reviewCount: 117,
    featured: false,
    bestseller: false,
    delivery: "Gift-ready box included.",
    notes: ["Deep oud", "Leather contrast"],
    images: [1, 2, 3],
    image360: 1,
    reviews: [],
    questions: []
  }),
  createProduct({
    slug: "black-oud-travel-trio",
    name: "Black Oud (Travel Trio)",
    category: "Luxury Collection",
    gender: "Men",
    fragranceFamily: "Oud",
    topNotes: ["Saffron", "Black Pepper", "Bergamot"],
    heartNotes: ["Oud", "Patchouli", "Cedarwood"],
    baseNotes: ["Leather", "Amber", "Musk"],
    occasion: "Evening",
    season: "Winter",
    sillage: "Strong",
    story: "A commanding oud fragrance with dark spice, leather and amber for a confident, magnetic signature.",
    howToWear: "Spray to pulse points and allow the oud to deepen through the evening.",
    whenToWear: "Ideal for business evenings, gala events and formal nights.",
    longevity: "10+ hours",
    projection: "Strong",
    size: "Travel Trio",
    price: 254,
    oldPrice: 297,
    discount: "14%",
    stock: 6,
    rating: 4.9,
    reviewCount: 83,
    featured: false,
    bestseller: false,
    delivery: "Gift-ready box included.",
    notes: ["Deep oud", "Leather contrast"],
    images: [1, 2, 3],
    image360: 1,
    reviews: [],
    questions: []
  }),
  createProduct({
    slug: "secret-oud",
    name: "Secret Oud",
    category: "Eau de Parfum",
    gender: "Unisex",
    fragranceFamily: "Oud",
    topNotes: ["Bergamot", "Cardamom", "Licorice"],
    heartNotes: ["Oud", "Iris", "Violet"],
    baseNotes: ["Vetiver", "Cedarwood", "Musk"],
    occasion: "Evening",
    season: "Autumn",
    sillage: "Moderate",
    story: "A discreet, refined oud with powdery florals and earthy woods for an elegant, mysterious presence.",
    howToWear: "Apply lightly to pulse points for a soft balayage of scent.",
    whenToWear: "Perfect for intimate evenings, gala occasions and refined gatherings.",
    longevity: "8\u201310 hours",
    projection: "Moderate",
    size: "100 ml",
    price: 219,
    oldPrice: 249,
    discount: "12%",
    stock: 14,
    rating: 4.7,
    reviewCount: 80,
    featured: false,
    bestseller: false,
    delivery: "Luxury delivery available.",
    notes: ["Iris oud", "Powdery woods"],
    images: [2, 3, 4],
    image360: 2
  }),
  createProduct({
    slug: "secret-oud-50-ml",
    name: "Secret Oud (50 ml)",
    category: "Eau de Parfum",
    gender: "Unisex",
    fragranceFamily: "Oud",
    topNotes: ["Bergamot", "Cardamom", "Licorice"],
    heartNotes: ["Oud", "Iris", "Violet"],
    baseNotes: ["Vetiver", "Cedarwood", "Musk"],
    occasion: "Evening",
    season: "Autumn",
    sillage: "Moderate",
    story: "A discreet, refined oud with powdery florals and earthy woods for an elegant, mysterious presence.",
    howToWear: "Apply lightly to pulse points for a soft balayage of scent.",
    whenToWear: "Perfect for intimate evenings, gala occasions and refined gatherings.",
    longevity: "8\u201310 hours",
    projection: "Moderate",
    size: "50 ml",
    price: 164,
    oldPrice: 187,
    discount: "12%",
    stock: 12,
    rating: 4.7,
    reviewCount: 60,
    featured: false,
    bestseller: false,
    delivery: "Luxury delivery available.",
    notes: ["Iris oud", "Powdery woods"],
    images: [2, 3, 4],
    image360: 2,
    reviews: [],
    questions: []
  }),
  createProduct({
    slug: "secret-oud-travel-duo",
    name: "Secret Oud (Travel Duo)",
    category: "Eau de Parfum",
    gender: "Unisex",
    fragranceFamily: "Oud",
    topNotes: ["Bergamot", "Cardamom", "Licorice"],
    heartNotes: ["Oud", "Iris", "Violet"],
    baseNotes: ["Vetiver", "Cedarwood", "Musk"],
    occasion: "Evening",
    season: "Autumn",
    sillage: "Moderate",
    story: "A discreet, refined oud with powdery florals and earthy woods for an elegant, mysterious presence.",
    howToWear: "Apply lightly to pulse points for a soft balayage of scent.",
    whenToWear: "Perfect for intimate evenings, gala occasions and refined gatherings.",
    longevity: "8\u201310 hours",
    projection: "Moderate",
    size: "Travel Duo",
    price: 197,
    oldPrice: 224,
    discount: "12%",
    stock: 12,
    rating: 4.7,
    reviewCount: 72,
    featured: false,
    bestseller: false,
    delivery: "Luxury delivery available.",
    notes: ["Iris oud", "Powdery woods"],
    images: [2, 3, 4],
    image360: 2,
    reviews: [],
    questions: []
  }),
  createProduct({
    slug: "secret-oud-gift-set",
    name: "Secret Oud (Gift Set)",
    category: "Eau de Parfum",
    gender: "Unisex",
    fragranceFamily: "Oud",
    topNotes: ["Bergamot", "Cardamom", "Licorice"],
    heartNotes: ["Oud", "Iris", "Violet"],
    baseNotes: ["Vetiver", "Cedarwood", "Musk"],
    occasion: "Evening",
    season: "Autumn",
    sillage: "Moderate",
    story: "A discreet, refined oud with powdery florals and earthy woods for an elegant, mysterious presence.",
    howToWear: "Apply lightly to pulse points for a soft balayage of scent.",
    whenToWear: "Perfect for intimate evenings, gala occasions and refined gatherings.",
    longevity: "8\u201310 hours",
    projection: "Moderate",
    size: "Gift Set",
    price: 263,
    oldPrice: 299,
    discount: "12%",
    stock: 12,
    rating: 4.7,
    reviewCount: 96,
    featured: false,
    bestseller: false,
    delivery: "Luxury delivery available.",
    notes: ["Iris oud", "Powdery woods"],
    images: [2, 3, 4],
    image360: 2,
    reviews: [],
    questions: []
  }),
  createProduct({
    slug: "secret-oud-travel-trio",
    name: "Secret Oud (Travel Trio)",
    category: "Eau de Parfum",
    gender: "Unisex",
    fragranceFamily: "Oud",
    topNotes: ["Bergamot", "Cardamom", "Licorice"],
    heartNotes: ["Oud", "Iris", "Violet"],
    baseNotes: ["Vetiver", "Cedarwood", "Musk"],
    occasion: "Evening",
    season: "Autumn",
    sillage: "Moderate",
    story: "A discreet, refined oud with powdery florals and earthy woods for an elegant, mysterious presence.",
    howToWear: "Apply lightly to pulse points for a soft balayage of scent.",
    whenToWear: "Perfect for intimate evenings, gala occasions and refined gatherings.",
    longevity: "8\u201310 hours",
    projection: "Moderate",
    size: "Travel Trio",
    price: 186,
    oldPrice: 212,
    discount: "12%",
    stock: 12,
    rating: 4.7,
    reviewCount: 68,
    featured: false,
    bestseller: false,
    delivery: "Luxury delivery available.",
    notes: ["Iris oud", "Powdery woods"],
    images: [2, 3, 4],
    image360: 2,
    reviews: [],
    questions: []
  }),
  createProduct({
    slug: "sandal",
    name: "Sandal",
    category: "Luxury Collection",
    gender: "Unisex",
    fragranceFamily: "Woody",
    topNotes: ["Cardamom", "Bergamot", "Nutmeg"],
    heartNotes: ["Sandalwood", "Rose", "Spice"],
    baseNotes: ["Oud", "Vanilla", "Cedarwood"],
    occasion: "Daytime",
    season: "All year",
    sillage: "Moderate",
    story: "A creamy sandalwood fragrance with warm spices and a luxurious woody base that feels timeless and rich.",
    howToWear: "Apply to the neck and chest for a soft, polished trail.",
    whenToWear: "Ideal for both day and evening wear, especially in cooler seasons.",
    longevity: "8\u201310 hours",
    projection: "Moderate",
    size: "100 ml",
    price: 199,
    oldPrice: 239,
    discount: "17%",
    stock: 17,
    rating: 4.8,
    reviewCount: 77,
    featured: false,
    bestseller: false,
    delivery: "Elegant gift wrap available on request.",
    notes: ["Creamy sandalwood", "Warm spice"],
    images: [4, 5, 6],
    image360: 4
  }),
  createProduct({
    slug: "sandal-50-ml",
    name: "Sandal (50 ml)",
    category: "Luxury Collection",
    gender: "Unisex",
    fragranceFamily: "Woody",
    topNotes: ["Cardamom", "Bergamot", "Nutmeg"],
    heartNotes: ["Sandalwood", "Rose", "Spice"],
    baseNotes: ["Oud", "Vanilla", "Cedarwood"],
    occasion: "Daytime",
    season: "All year",
    sillage: "Moderate",
    story: "A creamy sandalwood fragrance with warm spices and a luxurious woody base that feels timeless and rich.",
    howToWear: "Apply to the neck and chest for a soft, polished trail.",
    whenToWear: "Ideal for both day and evening wear, especially in cooler seasons.",
    longevity: "8\u201310 hours",
    projection: "Moderate",
    size: "50 ml",
    price: 149,
    oldPrice: 179,
    discount: "17%",
    stock: 15,
    rating: 4.8,
    reviewCount: 57,
    featured: false,
    bestseller: false,
    delivery: "Elegant gift wrap available on request.",
    notes: ["Creamy sandalwood", "Warm spice"],
    images: [4, 5, 6],
    image360: 4,
    reviews: [],
    questions: []
  }),
  createProduct({
    slug: "sandal-travel-duo",
    name: "Sandal (Travel Duo)",
    category: "Luxury Collection",
    gender: "Unisex",
    fragranceFamily: "Woody",
    topNotes: ["Cardamom", "Bergamot", "Nutmeg"],
    heartNotes: ["Sandalwood", "Rose", "Spice"],
    baseNotes: ["Oud", "Vanilla", "Cedarwood"],
    occasion: "Daytime",
    season: "All year",
    sillage: "Moderate",
    story: "A creamy sandalwood fragrance with warm spices and a luxurious woody base that feels timeless and rich.",
    howToWear: "Apply to the neck and chest for a soft, polished trail.",
    whenToWear: "Ideal for both day and evening wear, especially in cooler seasons.",
    longevity: "8\u201310 hours",
    projection: "Moderate",
    size: "Travel Duo",
    price: 179,
    oldPrice: 215,
    discount: "17%",
    stock: 15,
    rating: 4.8,
    reviewCount: 69,
    featured: false,
    bestseller: false,
    delivery: "Elegant gift wrap available on request.",
    notes: ["Creamy sandalwood", "Warm spice"],
    images: [4, 5, 6],
    image360: 4,
    reviews: [],
    questions: []
  })
];

export const getProducts = () => products;
export const getProductBySlug = (slug) => products.find((product) => product.slug === slug);
export const getFeaturedProducts = () => products.filter((product) => product.featured);
export const getBestSellers = () => products.filter((product) => product.bestseller);
export const getProductsByGender = (gender) => products.filter((product) => product.gender === gender || product.gender === 'Unisex');
export const getProductsByCategory = (category) => products.filter((product) => product.category === category);