import perfume1 from '../assets/perfumes/perfume1.jpeg';
import perfume2 from '../assets/perfumes/perfume2.jpeg';
import perfume3 from '../assets/perfumes/perfume3.jpeg';
import perfume4 from '../assets/perfumes/perfume4.jpeg';
import perfume5 from '../assets/perfumes/perfume5.jpeg';
import perfume6 from '../assets/perfumes/perfume6.jpeg';
import perfume7 from '../assets/perfumes/perfume7.jpeg';
import perfume8 from '../assets/perfumes/perfume8.jpeg';
import perfume9 from '../assets/perfumes/perfume9.jpeg';

export const products = [
  {
    id: 'oud-mari',
    slug: 'oud-kraft-mari',
    name: 'Oud Kraft Mari',
    category: 'Signature',
    gender: 'Unisex',
    inspiration: 'Golden desert evenings and velvet evenings in the capital.',
    description: 'An elegant signature blend with warm oud, amber and soft woods for a memorable impression.',
    price: 129,
    oldPrice: 159,
    size: '100 ml',
    images: [perfume1, perfume2],
    fragranceFamily: 'Oud',
    topNotes: ['Bergamot', 'Cardamom'],
    middleNotes: ['Rose Absolute', 'Cedarwood'],
    baseNotes: ['Oud', 'Amber', 'Musk'],
    longevity: '8–10 hours',
    projection: 'Moderate',
    stock: 12,
    rating: 4.9,
    reviews: 128,
    featured: true,
    bestSeller: true
  },
  {
    id: 'oud-emerald',
    slug: 'oud-kraft-emerald',
    name: 'Oud Kraft Emerald',
    category: 'Signature',
    gender: 'Men',
    inspiration: 'Refined confidence for evenings and formal gatherings.',
    description: 'A deep, polished fragrance that balances green freshness with woody depth.',
    price: 99,
    oldPrice: 129,
    size: '100 ml',
    images: [perfume2, perfume3],
    fragranceFamily: 'Woody',
    topNotes: ['Green Apple', 'Pink Pepper'],
    middleNotes: ['Vetiver', 'Geranium'],
    baseNotes: ['Oud', 'Cypress', 'Patchouli'],
    longevity: '6–8 hours',
    projection: 'Strong',
    stock: 9,
    rating: 4.7,
    reviews: 84,
    featured: true,
    bestSeller: false
  },
  {
    id: 'oud-noir',
    slug: 'oud-kraft-noir',
    name: 'Oud Kraft Noir',
    category: 'Signature',
    gender: 'Unisex',
    inspiration: 'Dark evenings, candlelight and a polished finish.',
    description: 'A rich and intimate fragrance with smooth smoke, amber and soft resin.',
    price: 149,
    oldPrice: 179,
    size: '100 ml',
    images: [perfume3, perfume4],
    fragranceFamily: 'Amber',
    topNotes: ['Black Tea', 'Saffron'],
    middleNotes: ['Jasmine', 'Labdanum'],
    baseNotes: ['Oud', 'Amber', 'Leather'],
    longevity: '10+ hours',
    projection: 'Strong',
    stock: 7,
    rating: 4.8,
    reviews: 96,
    featured: true,
    bestSeller: true
  },
  {
    id: 'oud-azure',
    slug: 'oud-kraft-azure',
    name: 'Oud Kraft Azure',
    category: 'Edition',
    gender: 'Women',
    inspiration: 'Fresh sea air and sunlit evenings by the coast.',
    description: 'A luminous citrus-amber scent that feels airy, elegant and modern.',
    price: 109,
    oldPrice: 139,
    size: '100 ml',
    images: [perfume4, perfume5],
    fragranceFamily: 'Fresh',
    topNotes: ['Lemon', 'Neroli'],
    middleNotes: ['White Tea', 'Jasmine'],
    baseNotes: ['Amberwood', 'Musk'],
    longevity: '5–7 hours',
    projection: 'Soft',
    stock: 10,
    rating: 4.6,
    reviews: 73,
    featured: true,
    bestSeller: false
  },
  {
    id: 'oud-rose',
    slug: 'oud-kraft-rose',
    name: 'Oud Kraft Rose',
    category: 'Edition',
    gender: 'Women',
    inspiration: 'A graceful evening bouquet with a warm, velvet base.',
    description: 'A graceful floral scent designed for gift giving and special occasions.',
    price: 119,
    oldPrice: 149,
    size: '100 ml',
    images: [perfume5, perfume6],
    fragranceFamily: 'Floral',
    topNotes: ['Pear', 'Pink Pepper'],
    middleNotes: ['Rose', 'Iris'],
    baseNotes: ['Praline', 'Musk'],
    longevity: '6–8 hours',
    projection: 'Moderate',
    stock: 8,
    rating: 4.8,
    reviews: 91,
    featured: false,
    bestSeller: true
  },
  {
    id: 'oud-amber',
    slug: 'oud-kraft-amber',
    name: 'Oud Kraft Amber',
    category: 'Signature',
    gender: 'Unisex',
    inspiration: 'Golden warmth wrapped in modern minimalism.',
    description: 'A radiant amber fragrance with a luxe trail and understated confidence.',
    price: 89,
    oldPrice: 119,
    size: '100 ml',
    images: [perfume6, perfume7],
    fragranceFamily: 'Amber',
    topNotes: ['Mandarin', 'Cardamom'],
    middleNotes: ['Amber', 'Cinnamon'],
    baseNotes: ['Oud', 'Vanilla', 'Musk'],
    longevity: '7–9 hours',
    projection: 'Moderate',
    stock: 11,
    rating: 4.7,
    reviews: 67,
    featured: true,
    bestSeller: false
  },
  {
    id: 'oud-velvet',
    slug: 'oud-kraft-velvet',
    name: 'Oud Kraft Velvet',
    category: 'Gift Edition',
    gender: 'Men',
    inspiration: 'A polished scent for gifting and celebratory evenings.',
    description: 'A smooth woody blend with soft amber and aromatic depth.',
    price: 139,
    oldPrice: 169,
    size: '100 ml',
    images: [perfume8, perfume9],
    fragranceFamily: 'Musk',
    topNotes: ['Juniper', 'Bergamot'],
    middleNotes: ['Lavender', 'Cedarwood'],
    baseNotes: ['Oud', 'Musk', 'Tonka'],
    longevity: '8–10 hours',
    projection: 'Moderate',
    stock: 6,
    rating: 4.9,
    reviews: 112,
    featured: false,
    bestSeller: true
  }
];

export const getProducts = () => products;
export const getProductBySlug = (slug) => products.find((product) => product.slug === slug);
export const getFeaturedProducts = () => products.filter((product) => product.featured);
export const getBestSellers = () => products.filter((product) => product.bestSeller);
export const getProductsByGender = (gender) => products.filter((product) => product.gender === gender || product.gender === 'Unisex');
export const getProductsByCategory = (category) => products.filter((product) => product.category === category);
